spring:
  application:
    name: gulimall-member

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hanbing0223
    url: jdbc:mysql://localhost:3306/gulimall_ums?serverTimezone=Asia/Shanghai

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.140.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000
