spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://ronghanbing.com
          predicates:
            - Query=url,ice
        - id: qq_route
          uri: https://qq.com
          predicates:
            - Query=url,qq